"""Movies Table

Revision ID: 0f758fbce435
Revises: 9cd8d4f6192b
Create Date: 2020-04-10 18:56:41.066612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f758fbce435'
down_revision = '9cd8d4f6192b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('director', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'director')
    # ### end Alembic commands ###
