"""Movies Table

Revision ID: 2a1469d2cdd7
Revises: 3246f9f5d7cd
Create Date: 2020-03-31 16:03:11.102096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1469d2cdd7'
down_revision = '3246f9f5d7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('plot', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('poster', sa.String(length=256), nullable=True))
    op.add_column('movies', sa.Column('rating', sa.String(length=12), nullable=True))
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'rating')
    op.drop_column('movies', 'poster')
    op.drop_column('movies', 'plot')
    # ### end Alembic commands ###
