"""votes table

Revision ID: 6e701eb7155d
Revises: 2d046c98ebea
Create Date: 2020-04-04 22:11:49.301740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e701eb7155d'
down_revision = '2d046c98ebea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_date'), 'votes', ['date'], unique=False)
    op.create_index(op.f('ix_votes_username'), 'votes', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_username'), table_name='votes')
    op.drop_index(op.f('ix_votes_date'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
