"""Movies table

Revision ID: 9cd8d4f6192b
Revises: caf7e5a413f9
Create Date: 2020-04-10 18:30:56.417708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd8d4f6192b'
down_revision = 'caf7e5a413f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genres')
    # ### end Alembic commands ###
