"""Users table

Revision ID: a396e3ea9ada
Revises: 2a1469d2cdd7
Create Date: 2020-04-01 13:35:18.754999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a396e3ea9ada'
down_revision = '2a1469d2cdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_vote', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_vote')
    # ### end Alembic commands ###
