"""movies table

Revision ID: caf7e5a413f9
Revises: 6e701eb7155d
Create Date: 2020-04-07 19:58:03.087277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf7e5a413f9'
down_revision = '6e701eb7155d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'category')
    # ### end Alembic commands ###
