"""Movies Table

Revision ID: fe12caf47c33
Revises: 0f758fbce435
Create Date: 2020-04-11 19:37:41.732135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12caf47c33'
down_revision = '0f758fbce435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'imdb_page')
    # ### end Alembic commands ###
